In [7]:
import pandas as pd
import numpy as np
import os
import analyzere

In [44]:
doc_col={
    "event_catalog":["EventID","Rate"],
    "yelt":["TrialId", "Sequence", "EventId", "Loss"],
    "yeqt":[],
    "er":[],
    "contract_terms":[]
    
}

In [2]:
df1 = pd.read_csv("catalog_correct.csv")
df2 = pd.read_csv("catalog_incorrect.csv")

In [7]:
df1.describe()

             EventID          Rate        ModelID
count  498000.000000  4.980000e+05  498000.000000
mean   249000.500000  1.000000e-03       5.469900
std    143760.361366  8.673626e-19       3.652611
min         1.000000  1.000000e-03       1.000000
25%    124500.750000  1.000000e-03       3.000000
50%    249000.500000  1.000000e-03       5.000000
75%    373500.250000  1.000000e-03       7.000000
max    498000.000000  1.000000e-03      15.000000

In [8]:
df1.columns

Index(['EventID', 'Rate', 'Region', 'Peril', 'SubRegion', 'ModelID'], dtype='object')

In [9]:
df1.dtypes

EventID        int64
Rate         float64
Region        object
Peril         object
SubRegion     object
ModelID        int64
dtype: object

In [10]:
df1.isnull()

        EventID   Rate  Region  Peril  SubRegion  ModelID
0         False  False   False  False      False    False
1         False  False   False  False      False    False
2         False  False   False  False      False    False
3         False  False   False  False      False    False
4         False  False   False  False      False    False
5         False  False   False  False      False    False
6         False  False   False  False      False    False
7         False  False   False  False      False    False
8         False  False   False  False      False    False
9         False  False   False  False      False    False
10        False  False   False  False      False    False
11        False  False   False  False      False    False
12        False  False   False  False      False    False
13        False  False   False  False      False    False
14        False  False   False  False      False    False
15        False  False   False  False      False    False
16        False  False   False  False      False    False
17        False  False   False  False      False    False
18        False  False   False  False      False    False
19        False  False   False  False      False    False
20        False  False   False  False      False    False
21        False  False   False  False      False    False
22        False  False   False  False      False    False
23        False  False   False  False      False    False
24        False  False   False  False      False    False
25        False  False   False  False      False    False
26        False  False   False  False      False    False
27        False  False   False  False      False    False
28        False  False   False  False      False    False
29        False  False   False  False      False    False
...         ...    ...     ...    ...        ...      ...
497970    False  False   False  False       True    False
497971    False  False   False  False       True    False
497972    False  False   False  False       True    False
497973    False  False   False  False       True    False
497974    False  False   False  False       True    False
497975    False  False   False  False       True    False
497976    False  False   False  False       True    False
497977    False  False   False  False       True    False
497978    False  False   False  False       True    False
497979    False  False   False  False       True    False
497980    False  False   False  False       True    False
497981    False  False   False  False       True    False
497982    False  False   False  False       True    False
497983    False  False   False  False       True    False
497984    False  False   False  False       True    False
497985    False  False   False  False       True    False
497986    False  False   False  False       True    False
497987    False  False   False  False       True    False
497988    False  False   False  False       True    False
497989    False  False   False  False       True    False
497990    False  False   False  False       True    False
497991    False  False   False  False       True    False
497992    False  False   False  False       True    False
497993    False  False   False  False       True    False
497994    False  False   False  False       True    False
497995    False  False   False  False       True    False
497996    False  False   False  False       True    False
497997    False  False   False  False       True    False
497998    False  False   False  False       True    False
497999    False  False   False  False       True    False

[498000 rows x 6 columns]

In [3]:
# converting data type
df2.describe()

             EventID          Rate        ModelID  Unnamed: 6
count  497999.000000  4.979800e+05  497980.000000         1.0
mean   249000.947289  1.000000e-03       5.469778        12.0
std    143760.159176  1.084203e-18       3.652567         NaN
min         1.000000  1.000000e-03       1.000000        12.0
25%    124501.500000  1.000000e-03       3.000000        12.0
50%    249001.000000  1.000000e-03       5.000000        12.0
75%    373500.500000  1.000000e-03       7.000000        12.0
max    498000.000000  1.000000e-03      15.000000        12.0

In [13]:
df2.dtypes

EventID       float64
Rate          float64
Region         object
Peril          object
SubRegion      object
ModelID       float64
Unnamed: 6    float64
dtype: object

In [14]:
df2.isnull()

        EventID   Rate  Region  Peril  SubRegion  ModelID  Unnamed: 6
0         False  False   False  False      False    False        True
1         False  False   False  False      False    False        True
2         False  False   False  False      False    False        True
3         False  False   False  False      False    False        True
4         False  False   False  False      False    False        True
5         False  False   False  False      False    False        True
6         False  False   False  False      False    False        True
7         False  False   False  False      False    False        True
8         False  False   False  False      False    False        True
9         False  False   False  False      False    False        True
10        False  False   False  False      False    False        True
11        False  False   False  False      False    False        True
12        False  False   False  False      False    False        True
13        False  False   False  False      False    False        True
14        False  False   False  False      False    False        True
15        False  False   False  False      False    False        True
16        False  False   False  False      False    False        True
17        False  False   False  False      False    False        True
18        False  False   False  False      False    False        True
19        False  False   False  False      False    False        True
20        False  False   False  False      False    False        True
21        False  False   False  False      False    False        True
22        False  False   False  False      False    False        True
23        False  False   False  False      False    False        True
24        False  False   False  False      False    False        True
25        False  False   False  False      False    False        True
26        False  False   False  False      False    False        True
27        False  False   False  False      False    False        True
28        False  False   False  False      False    False        True
29        False  False   False  False      False    False        True
...         ...    ...     ...    ...        ...      ...         ...
497970    False  False   False  False       True    False        True
497971    False  False   False  False       True    False        True
497972    False  False   False  False       True    False        True
497973    False  False   False  False       True    False        True
497974    False  False   False  False       True    False        True
497975    False  False   False  False       True    False        True
497976    False  False   False  False       True    False        True
497977    False  False   False  False       True    False        True
497978    False  False   False  False       True    False        True
497979    False  False   False  False       True    False        True
497980    False  False   False  False       True    False        True
497981    False  False   False  False       True    False        True
497982    False  False   False  False       True    False        True
497983    False  False   False  False       True    False        True
497984    False  False   False  False       True    False        True
497985    False  False   False  False       True    False        True
497986    False  False   False  False       True    False        True
497987    False  False   False  False       True    False        True
497988    False  False   False  False       True    False        True
497989    False  False   False  False       True    False        True
497990    False  False   False  False       True    False        True
497991    False  False   False  False       True    False        True
497992    False  False   False  False       True    False        True
497993    False  False   False  False       True    False        True
497994    False  False   False  False       True    False        True
497995    False  False   False  False       True    False        True
497996    False  False   False  False       True    False        True
497997    False  False   False  False       True    False        True
497998    False  False   False  False       True    False        True
497999    False  False   False  False       True    False        True

[498000 rows x 7 columns]

In [15]:
df2.columns

Index(['EventID', 'Rate', 'Region', 'Peril', 'SubRegion', 'ModelID',
       'Unnamed: 6'],
      dtype='object')

In [16]:
df1.columns

Index(['EventID', 'Rate', 'Region', 'Peril', 'SubRegion', 'ModelID'], dtype='object')

In [17]:
with open("catalog_incorrect.csv","r") as f:
    for _ in range(10):
        print(f.readline())

EventID,Rate,Region,Peril,SubRegion,ModelID,

1,0.001,US,HU,Florida,1,

2,0.001,US,HU,Florida,1,

3,0.001,US,HU,Florida,1,

4,0.001,US,HU,Florida,1,

5,0.001,US,HU,Florida,1,

6,0.001,US,HU,Florida,1,

7,0.001,US,HU,Florida,1,

8,0.001,US,HU,Florida,1,

9,0.001,US,HU,Florida,1,

In [18]:
# document identification by columns
df2.columns
for k,v in doc_col.items():
    x = [x for x in v if x in df2.columns]
    if x==v:
        print(k)
        break

Index(['EventID', 'Rate', 'Region', 'Peril', 'SubRegion', 'ModelID',
       'Unnamed: 6'],
      dtype='object')

event_catalog

In [48]:
# check for datatype
df2.dtypes

EventID       float64
Rate          float64
Region         object
Peril          object
SubRegion      object
ModelID       float64
Unnamed: 6    float64
dtype: object

In [77]:
if df2.dtypes["EventID"] == "int64":
    print("OK")
else:
    print("EventID is not int")

EventID is not int

In [79]:
# check for uunique event_id
if len(df2.EventID.unique()) != len(df2["EventID"]):
    print("Event ID are not unique")
else:
    print("OK")

OK

In [64]:
df2["EventID"].fillna(0).astype("int64")

0              1
1              2
2              3
3              4
4              5
5              6
6              7
7              8
8              9
9             10
10            11
11            12
12            13
13            14
14            15
15            16
16            17
17            18
18            19
19            20
20            21
21            22
22            23
23            24
24            25
25            26
26            27
27            28
28            29
29            30
           ...
497970    497971
497971    497972
497972    497973
497973    497974
497974    497975
497975    497976
497976    497977
497977    497978
497978    497979
497979    497980
497980    497981
497981    497982
497982    497983
497983    497984
497984    497985
497985    497986
497986    497987
497987    497988
497988    497989
497989    497990
497990    497991
497991    497992
497992    497993
497993    497994
497994    497995
497995    497996
497996    497997
497997    497998
497998    497999
497999    498000
Name: EventID, Length: 498000, dtype: int64

In [65]:
df1["EventID"].astype("int")

0              1
1              2
2              3
3              4
4              5
5              6
6              7
7              8
8              9
9             10
10            11
11            12
12            13
13            14
14            15
15            16
16            17
17            18
18            19
19            20
20            21
21            22
22            23
23            24
24            25
25            26
26            27
27            28
28            29
29            30
           ...
497970    497971
497971    497972
497972    497973
497973    497974
497974    497975
497975    497976
497976    497977
497977    497978
497978    497979
497979    497980
497980    497981
497981    497982
497982    497983
497983    497984
497984    497985
497985    497986
497986    497987
497987    497988
497988    497989
497989    497990
497990    497991
497991    497992
497992    497993
497993    497994
497994    497995
497995    497996
497996    497997
497997    497998
497998    497999
497999    498000
Name: EventID, Length: 498000, dtype: int32

In [103]:
# check for ascending order
# df2["EventID"].diff()[1:].apply(lambda x: True if x>0 else False).all()
for x in df2["EventID"].diff()[1:].apply(lambda x: True if x>0 else False):
    if not x:
        print(x)

False
False

In [102]:
z = [a for a in df2["EventID"].diff()[1:] if a!=1]
print(z)

[nan, nan]

In [4]:
class event_catalog:
    def __init__(self,data):
        self.data = pd.read_csv(data)
    def data_type(self):
        if self.data.dtypes["EventID"] == "int64":
            print("Event ID is int : OK")
        else:
            print("EventID is not int")
    def unique_eventid(self):
        if len(self.data["EventID"].unique()) != len(self.data["EventID"]):
            print("Event ID are not unique")
        else:
            print("Event ID are unique : OK")
    def ascending(self):
        if self.data["EventID"].diff()[1:].apply(lambda x: True if x>0 else False).all():
            print("EventID are in ascending order")
        else:
            print("EventID are not in ascending order or may contain null values")
    def apply_checks(self):
        self.data_type()
        self.unique_eventid()
        self.ascending()

In [5]:
a = event_catalog("catalog_incorrect.csv")

In [4]:
a.data_type()

EventID is not int

In [5]:
a.unique_eventid()

Event ID are unique : OK

In [13]:
a.apply_checks()

EventID is not int
Event ID are unique : OK
EventID are not in ascending order or may contain null values

In [14]:
analyzere.base_url = 'https://hackathon-api.analyzere.net/'
analyzere.username = 'possibleparrots'
analyzere.password = 'Zahk8ic9'

In [18]:
from analyzere import EventCatalog
catalog = EventCatalog(description='hackathon_test',
                       tags=['shiftkey',],
                       source='hackthon').save()
with open('catalog_correct.csv') as catalog_data:
    c = event_catalog(catalog_data)
    c.applycheck()
    x=catalog.upload_data(catalog_data)
    print(x)

In [16]:
EventCatalog.list()

[<EventCatalog id=a2d9fb3a-b60b-489d-8a6d-1ef738353186 at 0x2432a4088d0> JSON: {
   "created": "2016-03-09T18:19:13.838480+00:00",
   "data": {
     "ref_id": "70d781fa-6f40-45b9-ae8a-692a94146c93"
   },
   "description": "Nova Re Model A",
   "id": "a2d9fb3a-b60b-489d-8a6d-1ef738353186",
   "meta_data": {},
   "modified": "2018-03-20T00:14:48.733606+00:00",
   "source": "Analyze Re",
   "status": "processing_succeeded",
   "status_message": null,
   "tags": []
 },
 <EventCatalog id=aa8c316c-128c-485b-9144-5eed3f051c36 at 0x2432a408ba8> JSON: {
   "created": "2016-03-09T18:21:12.527875+00:00",
   "data": {
     "ref_id": "9bb95534-4655-4bdd-960d-ac95b5c80a26"
   },
   "description": "Nova Re Model B",
   "id": "aa8c316c-128c-485b-9144-5eed3f051c36",
   "meta_data": {},
   "modified": "2018-03-20T00:14:48.779246+00:00",
   "source": "Analyze Re",
   "status": "processing_succeeded",
   "status_message": null,
   "tags": []
 },
 <EventCatalog id=4486e01e-a137-4413-b8f5-235541edba0e at 0x2432a408c88> JSON: {
   "created": "2017-08-21T17:03:30.305752+00:00",
   "data": {
     "ref_id": "18258e2d-62fa-4ee8-b2d8-9865a3c174fd"
   },
   "description": "AIR 10k WWAP",
   "id": "4486e01e-a137-4413-b8f5-235541edba0e",
   "meta_data": {},
   "modified": "2018-03-20T00:14:48.865046+00:00",
   "source": "AIR",
   "status": "processing_succeeded",
   "status_message": null,
   "tags": []
 },
 <EventCatalog id=c6b5974a-6cb8-4e4f-93fc-ef4c9ffc907d at 0x2432a408eb8> JSON: {
   "created": "2017-10-11T18:23:03.864131+00:00",
   "data": {
     "ref_id": "a6c63a8d-357c-4b49-b720-d752ebf9f74d"
   },
   "description": "Generated for ParametricLossSet[5d51d919-2455-4594-9206-7794e22da252]",
   "id": "c6b5974a-6cb8-4e4f-93fc-ef4c9ffc907d",
   "meta_data": {},
   "modified": "2018-03-20T00:14:48.891413+00:00",
   "source": null,
   "status": "processing_succeeded",
   "status_message": null,
   "tags": null
 },
 <EventCatalog id=5b3598ad-27c9-4cbc-9046-fa9b284f7733 at 0x2432a420160> JSON: {
   "created": "2017-10-12T08:22:21.896149+00:00",
   "data": {
     "ref_id": "7c637b4a-d0d3-43ba-ab0f-e3f2c3b119a1"
   },
   "description": "Generated for ParametricLossSet[470b3a23-4c78-42c7-8e74-cb1f07ea109e]",
   "id": "5b3598ad-27c9-4cbc-9046-fa9b284f7733",
   "meta_data": {},
   "modified": "2018-03-20T00:14:48.919175+00:00",
   "source": null,
   "status": "processing_succeeded",
   "status_message": null,
   "tags": null
 },
 <EventCatalog id=08eee021-58bc-4b0f-a1e4-17b93372d1b2 at 0x2432a420518> JSON: {
   "created": "2019-03-09T16:34:34.992980+00:00",
   "data": {
     "ref_id": "01f7ccd2-ffbf-41f2-b127-92accfe30ac2"
   },
   "description": "Hackathon Test Catalog (Oliver)",
   "id": "08eee021-58bc-4b0f-a1e4-17b93372d1b2",
   "meta_data": {},
   "modified": "2019-03-09T16:45:35.472295+00:00",
   "source": null,
   "status": "processing_succeeded",
   "status_message": null,
   "tags": []
 },
 <EventCatalog id=bd4a142d-e3bc-49ee-a172-2a12fd825a2a at 0x2432a4205c0> JSON: {
   "created": "2019-03-09T16:46:03.817648+00:00",
   "data": {
     "ref_id": "174255c9-0c7f-467b-8172-4ee8a662de2a"
   },
   "description": "Hackathon Test Catalog (Oliver)",
   "id": "bd4a142d-e3bc-49ee-a172-2a12fd825a2a",
   "meta_data": {},
   "modified": "2019-03-09T16:48:20.621634+00:00",
   "source": null,
   "status": "processing_failed",
   "status_message": "Row 26251: Unable to process event: could not convert string to float: .",
   "tags": []
 }]

In [19]:
catalog

<EventCatalog id=6dcc4f55-f204-44d2-aa2f-71b313e4f3a2 at 0x2432a43b048> JSON: {
  "created": "2019-03-09T17:40:09.060604+00:00",
  "data": null,
  "description": "hackathon_test",
  "id": "6dcc4f55-f204-44d2-aa2f-71b313e4f3a2",
  "meta_data": {},
  "modified": "2019-03-09T17:40:09.060604+00:00",
  "source": "hackthon",
  "status": "ready",
  "status_message": null,
  "tags": [
    "shiftkey"
  ]
}

In [24]:
pd.read_csv("yelt_incorrect.csv",warn_bad_lines = True,error_bad_lines = False)

b'Skipping line 19: expected 4 fields, saw 5\nSkipping line 29: expected 4 fields, saw 5\n'
b'Skipping line 437229: expected 4 fields, saw 6\nSkipping line 437408: expected 4 fields, saw 5\n'

        TrialId  EventId     Sequence          Loss
0             1     5732     5.510562  8.796626e+04
1             1    28362    17.932175  9.953189e+02
2             1    32606    29.563548  1.610998e+03
3             1    32053    32.628220  2.552775e+03
4             1    41951    46.674760  2.250096e+04
5             1    37797    50.135909  2.897925e+03
6             1    41482    67.520135  4.781452e+03
7             1    31535    73.878925  1.790297e+03
8             1    44104   101.209138  5.423879e+03
9             1    42123   113.999240  1.098404e+04
10            1    46093   114.025049  7.330027e+03
11            1    37835   115.721234  2.014315e+03
12            1    31706   152.142859  2.899089e+03
13            1    30717   160.727490  1.531806e+03
14            1    25197   176.007257  1.243875e+03
15            1    36585   181.798881  2.125788e+04
16            1    28057   189.488288  8.978968e+03
17            1    47076   196.905672  1.471647e+04
18            1    24927   210.486481  1.137108e+03
19            1    47546   242.379214  2.981943e+04
20            1    45028   246.216595  2.334733e+03
21            1    37843   248.856537  8.872406e+02
22            1     4059   249.228921  3.636074e+06
23            1    25394   256.121032  7.697560e+02
24            1    42581   260.304726  2.695969e+03
25            1    41429   260.392737  1.546023e+05
26            1     4943   320.169466  1.177515e+07
27            1    34381   322.643538  1.874256e+03
28            1    46542   333.887040  2.146483e+04
29            1     4039   338.285582  4.662314e+06
...         ...      ...          ...           ...
437376    10000     4909   173.089252  3.535770e+07
437377    10000    45354   189.427246  2.835471e+03
437378    10000     6692   195.490294  9.743333e+04
437379    10000    26129   207.461165  7.959246e+02
437380    10000    32997   209.239385  1.386292e+03
437381    10000     5788   216.180213  4.254870e+04
437382    10000    43570   223.241866  4.272122e+03
437383    10000    21365   225.012598  2.048225e+05
437384    10000    32803   239.766258  8.535602e+02
437385    10000    26932   241.853040  2.679446e+03
437386    10000     9293   275.248364  3.536940e+04
437387    10000    39568   277.016348  3.184757e+03
437388    10000    42017   295.273162  5.314348e+04
437389    10000     5943   319.878260  2.020384e+04
437390    10000    29008   324.443990  5.174126e+02
437391    10000     6552   328.609204  8.083111e+04
437392    10000    33842   330.368501  1.110736e+04
437393    10000    45616   342.844431  7.832302e+03
437394    10000        0  1096.000000  2.385454e+04
437395    10000        0  1096.000000  8.904188e+05
437396    10000        0  1096.000000  4.178568e+05
437397    10000        0  1096.000000  9.130452e+05
437398    10000        0  1096.000000  5.193713e+07
437399    10000        0  1096.000000  4.188805e+05
437400    10000        0  1096.000000  7.915679e+05
437401    10000        0  1096.000000  8.483336e+04
437402    10000        0  1096.000000  1.175848e+05
437403    10000        0  1096.000000  5.366519e+04
437404    10000        0  1096.000000  1.126232e+05
437405    10000        0  1096.000000  1.759197e+06

[437406 rows x 4 columns]