In [1]:
import pandas as pd
import numpy as np
import os

In [44]:
doc_col={
    "event_catalog":["EventID","Rate"],
    "yelt":["TrialId", "Sequence", "EventId", "Loss"],
    "yeqt":[],
    "er":[],
    "contract_terms":[]
    
}

In [2]:
df1 = pd.read_csv("catalog_correct.csv")
df2 = pd.read_csv("catalog_incorrect.csv")

In [7]:
df1.describe()

             EventID          Rate        ModelID
count  498000.000000  4.980000e+05  498000.000000
mean   249000.500000  1.000000e-03       5.469900
std    143760.361366  8.673626e-19       3.652611
min         1.000000  1.000000e-03       1.000000
25%    124500.750000  1.000000e-03       3.000000
50%    249000.500000  1.000000e-03       5.000000
75%    373500.250000  1.000000e-03       7.000000
max    498000.000000  1.000000e-03      15.000000

In [8]:
df1.columns

Index(['EventID', 'Rate', 'Region', 'Peril', 'SubRegion', 'ModelID'], dtype='object')

In [9]:
df1.dtypes

EventID        int64
Rate         float64
Region        object
Peril         object
SubRegion     object
ModelID        int64
dtype: object

In [10]:
df1.isnull()

        EventID   Rate  Region  Peril  SubRegion  ModelID
0         False  False   False  False      False    False
1         False  False   False  False      False    False
2         False  False   False  False      False    False
3         False  False   False  False      False    False
4         False  False   False  False      False    False
5         False  False   False  False      False    False
6         False  False   False  False      False    False
7         False  False   False  False      False    False
8         False  False   False  False      False    False
9         False  False   False  False      False    False
10        False  False   False  False      False    False
11        False  False   False  False      False    False
12        False  False   False  False      False    False
13        False  False   False  False      False    False
14        False  False   False  False      False    False
15        False  False   False  False      False    False
16        False  False   False  False      False    False
17        False  False   False  False      False    False
18        False  False   False  False      False    False
19        False  False   False  False      False    False
20        False  False   False  False      False    False
21        False  False   False  False      False    False
22        False  False   False  False      False    False
23        False  False   False  False      False    False
24        False  False   False  False      False    False
25        False  False   False  False      False    False
26        False  False   False  False      False    False
27        False  False   False  False      False    False
28        False  False   False  False      False    False
29        False  False   False  False      False    False
...         ...    ...     ...    ...        ...      ...
497970    False  False   False  False       True    False
497971    False  False   False  False       True    False
497972    False  False   False  False       True    False
497973    False  False   False  False       True    False
497974    False  False   False  False       True    False
497975    False  False   False  False       True    False
497976    False  False   False  False       True    False
497977    False  False   False  False       True    False
497978    False  False   False  False       True    False
497979    False  False   False  False       True    False
497980    False  False   False  False       True    False
497981    False  False   False  False       True    False
497982    False  False   False  False       True    False
497983    False  False   False  False       True    False
497984    False  False   False  False       True    False
497985    False  False   False  False       True    False
497986    False  False   False  False       True    False
497987    False  False   False  False       True    False
497988    False  False   False  False       True    False
497989    False  False   False  False       True    False
497990    False  False   False  False       True    False
497991    False  False   False  False       True    False
497992    False  False   False  False       True    False
497993    False  False   False  False       True    False
497994    False  False   False  False       True    False
497995    False  False   False  False       True    False
497996    False  False   False  False       True    False
497997    False  False   False  False       True    False
497998    False  False   False  False       True    False
497999    False  False   False  False       True    False

[498000 rows x 6 columns]

In [12]:
# converting data type
df2.describe()

             EventID          Rate        ModelID  Unnamed: 6
count  497999.000000  4.979800e+05  497980.000000         1.0
mean   249000.947289  1.000000e-03       5.469778        12.0
std    143760.159176  1.084203e-18       3.652567         NaN
min         1.000000  1.000000e-03       1.000000        12.0
25%    124501.500000  1.000000e-03       3.000000        12.0
50%    249001.000000  1.000000e-03       5.000000        12.0
75%    373500.500000  1.000000e-03       7.000000        12.0
max    498000.000000  1.000000e-03      15.000000        12.0

In [13]:
df2.dtypes

EventID       float64
Rate          float64
Region         object
Peril          object
SubRegion      object
ModelID       float64
Unnamed: 6    float64
dtype: object

In [14]:
df2.isnull()

        EventID   Rate  Region  Peril  SubRegion  ModelID  Unnamed: 6
0         False  False   False  False      False    False        True
1         False  False   False  False      False    False        True
2         False  False   False  False      False    False        True
3         False  False   False  False      False    False        True
4         False  False   False  False      False    False        True
5         False  False   False  False      False    False        True
6         False  False   False  False      False    False        True
7         False  False   False  False      False    False        True
8         False  False   False  False      False    False        True
9         False  False   False  False      False    False        True
10        False  False   False  False      False    False        True
11        False  False   False  False      False    False        True
12        False  False   False  False      False    False        True
13        False  False   False  False      False    False        True
14        False  False   False  False      False    False        True
15        False  False   False  False      False    False        True
16        False  False   False  False      False    False        True
17        False  False   False  False      False    False        True
18        False  False   False  False      False    False        True
19        False  False   False  False      False    False        True
20        False  False   False  False      False    False        True
21        False  False   False  False      False    False        True
22        False  False   False  False      False    False        True
23        False  False   False  False      False    False        True
24        False  False   False  False      False    False        True
25        False  False   False  False      False    False        True
26        False  False   False  False      False    False        True
27        False  False   False  False      False    False        True
28        False  False   False  False      False    False        True
29        False  False   False  False      False    False        True
...         ...    ...     ...    ...        ...      ...         ...
497970    False  False   False  False       True    False        True
497971    False  False   False  False       True    False        True
497972    False  False   False  False       True    False        True
497973    False  False   False  False       True    False        True
497974    False  False   False  False       True    False        True
497975    False  False   False  False       True    False        True
497976    False  False   False  False       True    False        True
497977    False  False   False  False       True    False        True
497978    False  False   False  False       True    False        True
497979    False  False   False  False       True    False        True
497980    False  False   False  False       True    False        True
497981    False  False   False  False       True    False        True
497982    False  False   False  False       True    False        True
497983    False  False   False  False       True    False        True
497984    False  False   False  False       True    False        True
497985    False  False   False  False       True    False        True
497986    False  False   False  False       True    False        True
497987    False  False   False  False       True    False        True
497988    False  False   False  False       True    False        True
497989    False  False   False  False       True    False        True
497990    False  False   False  False       True    False        True
497991    False  False   False  False       True    False        True
497992    False  False   False  False       True    False        True
497993    False  False   False  False       True    False        True
497994    False  False   False  False       True    False        True
497995    False  False   False  False       True    False        True
497996    False  False   False  False       True    False        True
497997    False  False   False  False       True    False        True
497998    False  False   False  False       True    False        True
497999    False  False   False  False       True    False        True

[498000 rows x 7 columns]

In [15]:
df2.columns

Index(['EventID', 'Rate', 'Region', 'Peril', 'SubRegion', 'ModelID',
       'Unnamed: 6'],
      dtype='object')

In [16]:
df1.columns

Index(['EventID', 'Rate', 'Region', 'Peril', 'SubRegion', 'ModelID'], dtype='object')

In [17]:
with open("catalog_incorrect.csv","r") as f:
    for _ in range(10):
        print(f.readline())

EventID,Rate,Region,Peril,SubRegion,ModelID,

1,0.001,US,HU,Florida,1,

2,0.001,US,HU,Florida,1,

3,0.001,US,HU,Florida,1,

4,0.001,US,HU,Florida,1,

5,0.001,US,HU,Florida,1,

6,0.001,US,HU,Florida,1,

7,0.001,US,HU,Florida,1,

8,0.001,US,HU,Florida,1,

9,0.001,US,HU,Florida,1,

In [18]:
# document identification by columns
df2.columns

Index(['EventID', 'Rate', 'Region', 'Peril', 'SubRegion', 'ModelID',
       'Unnamed: 6'],
      dtype='object')

In [46]:
for k,v in doc_col.items():
    x = [x for x in v if x in df2.columns]
    if x==v:
        print(k)

event_catalog
yelt
yeqt
er
contract_terms